language: python

python:
  - "3.6"

services:
  - docker

before_script:
  - pip install -r requirements.txt

script:
  - docker-compose -f docker-compose.yml up --build -d
  - docker exec python ./manage.py migrate
  - docker exec python ./manage.py collectstatic --no-input
  - docker exec python ./manage.py test app
