language: python

services:
  - docker
  
before_install:
  - docker-compose -f ./Activity2/docker-compose.yml down
  - docker-compose -f ./Activity2/docker-compose.yml up -d

#script:
 # - pytest <name of file>
