version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - 5500:5432
    environment:
      POSTGRES_DB: 'mytube'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'Ffa8AbQKeBmuSYs4weU'
  python:
    container_name: python
    build: ./docker/python
    volumes:
      - ./videosite:/var/www/html
    working_dir: /var/www/html
    environment:
      DJANGO_DEBUG: 'False'
    depends_on:
      - postgres
  web:
    container_name: web
    build: ./docker/nginx
    ports:
      - 4000:80
    volumes:
      - ./videosite:/var/www/html
    working_dir: /etc/nginx
    links:
      - python
